all:
	g++ -std=c++17 default-main.cpp -o def-main -lpthread -O3 -g
	g++ -std=c++17 default-main-approach1.cpp -o def-main-a1 -lpthread -O3 -g
	g++ -std=c++17 default-main-approach2.cpp -o def-main-a2 -lpthread -O3 -g

clean:
	rm -rf *o def-main def-main-a1 def-main-a2
