#include <iostream>
#include <thread>
#include <atomic>
#include <list>
#include "Util/Timer.cpp"
#include "Util/FILEOPR.cpp"
#include "Contract/MixSCV.cpp"
#include "Graph/Lockfree/Graph.cpp"

#define MAX_THREADS 128
#define maxCoinAObj 5000  //maximum coin contract \account\ object.
#define CFCount 3         //# methods in coin contract.

#define maxPropObj 1000   //maximum ballot contract \proposal\ shared object.
#define maxVoterObj 40000 //maximum ballot contract \voter\ shared object.
#define BFCount 5         //# methods in ballot contract.

#define maxBidrObj 5000   //maximum simple auction contract \bidder\ shared object.
#define maxbEndT 600      //maximum simple auction contract \bidding time out\ duration.
#define AFConut 6         //# methods in simple auction contract.
#define pl "=================================================================\n"
#define MValidation true  //! true or false
#define numValidator 50
#define InitBalance 1000
#define NumBlock 26       //! at least two blocks, the first run is warmup run.
#define malMiner true     //! set the flag to make miner malicious.
#define NumOfDoubleSTx 2   //! # double-spending Tx for malicious final state by Miner, multiple of 2.


using namespace std;
using namespace std::chrono;

//! INPUT FROM INPUT FILE.
int nThread;    //! # of concurrent threads;
int numAUs;     //! # Atomic Unites to be executed.
int CoinSObj;   //! # Coin Shared Object.
int nProposal;  //! # Ballot Proposal Shared Object.
int nVoter;     //! # Ballot Voter Shared Object.
int nBidder;    //! # Ballot Voter Shared Object.
int bidEndT;    //! time duration for auction.
int lemda;      //!  % of edges to be removed from BG by malicious Miner.

double tTime[2];           //! total time taken by miner & validator.
int    *aCount;            //! Invalid transaction count.
Graph  *cGraph;            //! conflict grpah generated by miner to be given to validator.
float_t *gTtime;           //! time taken by each miner Thread to add edges and nodes in the conflict graph.
float_t*mTTime;            //! time taken by each miner Thread to execute AUs.
float_t*vTTime;            //! time taken by each validator Thread to execute AUs.
vector<string>listAUs;     //! AUs to be executed on contracts: index+1 => AU_ID.
std::atomic<int>currAU;    //! used by miner-thread to get index of AU to execute.
std::atomic<int>gNodeCount;//! # of valid AU node added in graph (invalid AUs will not be part of the graph & conflict list).
std::atomic<int>eAUCount;  //! used by validator threads to keep track of how many valid AUs executed by validator threads.
std::atomic<int>*mAUT;     //! array to map AUs to Trans id (time stamp); mAUT[index] = TransID, index+1 = AU_ID.
string *proposalNames;     //! proposal names for ballot contract.
std::atomic<int>*status;   //! used by pool threads:: -1 = thread join; 0 = wait; 1 = execute AUs given in ref[].
Graph::Graph_Node **Gref;  //! used by pool threads:: graph node (AU) reference to be execute by respective Pool thread.
std::atomic<bool>mm;       //! miner is malicious, this is used by validators.
Graph  *nValBG;            //! used to store graph of respective n validators.

//! CONTRACT OBJECTS;
Coin   *coin;            //! coin contract miner object.
Ballot *ballot;          //! ballot contract for miner object.
SimpleAuction *auction;  //! simple auction contract for miner object.

int *mCoinState;
int *vCoinState;
int *mBallotProState;
int *vBallotProState;
int *mBallotVotState;
int *vBallotVotState;
int mHBidder;
int mHBid;
int vHBidder;
int vHBid;
int *mPendingRet;
int *vPendingRet;



/*************************Miner code begins************************************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    Class "Miner" CREATE & RUN "n" miner-THREAD CONCURRENTLY           !
!"concMiner()" CALLED BY miner-THREAD TO PERFROM oprs of RESPECTIVE AUs !
! THREAD 0 IS CONSIDERED AS MINTER-THREAD (SMART CONTRACT DEPLOYER)     !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
class Miner
{
	public:
	Miner(int contDeployer)
	{
		cGraph = new Graph();

		//! initialize the counter used to execute the numAUs to.
		//! 0, and graph node counter to 0 (number of AUs added.
		//! in graph, invalid AUs will not part be of the grpah).
		currAU     = 0;
		gNodeCount = 0;

		proposalNames = new string[nProposal+1];
		for(int x = 0; x <= nProposal; x++)
			proposalNames[x] = "X"+to_string(x+1);


		//! index location represents respective thread id.
		mTTime = new float_t [nThread];
		gTtime = new float_t [nThread];
		aCount = new int [nThread];
		
		for(int i = 0; i < nThread; i++) 
		{
			mTTime[i] = 0;
			gTtime[i] = 0;
			aCount[i] = 0;
		}
		//! id of the contract creater is "minter_id = 5000".
		coin = new Coin( CoinSObj, 5000 );
		
		//! Id of the contract creater is \chairperson = 10000\.
		ballot = new Ballot( proposalNames, 10000, nVoter, nProposal);
		
		//! fixed beneficiary id to 0, it can be any unique address/id.
		auction = new SimpleAuction(bidEndT, 0, nBidder);
	}

	//!---------------------------------------------------- 
	//!!!!!!!! MAIN MINER:: CREATE MINER THREADS !!!!!!!!!!
	//!----------------------------------------------------
	void mainMiner()
	{
		Timer mTimer;
		thread T[nThread];


		//! initialization of account with
		//! fixed ammount; mint_m() is serial.
		int ts, bal = InitBalance, total = 0;
		for(int sid = 1; sid <= CoinSObj; sid++) 
		{
			//! 5000 is contract deployer.
			coin->mint_m(5000, sid, bal, &ts);
			total = total + bal;
		}

		//! Give \`voter\` the right to vote on this ballot.
		//! giveRightToVote_m() is serial.
		for(int voter = 1; voter <= nVoter; voter++) 
		{
			//! 10000 is chairperson.
			ballot->giveRightToVote_m(10000, voter);
		}


		//!--------------------------------------------------------
		//!!!!!!!!!!    Create nThread Miner threads      !!!!!!!!!
		//!--------------------------------------------------------
		//! Start clock to get time taken by miner algorithm.
		double start = mTimer.timeReq();
		for(int i = 0; i < nThread; i++)
			T[i] = thread(concMiner, i, numAUs, cGraph);

		//! miner thread join
		for(auto& th : T) th.join();

		//! Stop clock
		tTime[0] = mTimer.timeReq() - start;


		//! print the final state of the shared objects.
		finalState();
	}

	//!------------------------------
	//! The function to be executed !
	//! by all the miner threads.   !
	//!------------------------------
	static void concMiner( int t_ID, int numAUs, Graph *cGraph)
	{
		Timer thTimer;

		//! flag is used to add valid AUs in Graph.
		//! (invalid AU: senders doesn't
		//! have sufficient balance to send).
		bool flag = true;

		//! get the current index, and increment it.
		int curInd = currAU++;

		//! statrt clock to get time taken by this.AU
		auto start = thTimer._timeStart();

		while( curInd < numAUs )
		{
			//! trns_id of STM_BTO_trans that
			//! successfully executed this AU.
			int t_stamp;

			//! trans_ids with which this
			//! AU.trans_id is conflicting.
			list<int>conf_list;
			conf_list.clear();
			//!get the AU to execute,
			//! which is of string type.
			istringstream ss(listAUs[curInd]);

			string tmp;
			//! AU_ID to Execute.
			ss >> tmp;

			int AU_ID = stoi(tmp);

			//! Function Name (smart contract).
			ss >> tmp;

			if(tmp.compare("get_bal") == 0)
			{
				//! get balance of SObj/id.
				ss >> tmp;
				int s_id = stoi(tmp);
				int bal  = 0;

				//! get_bal of smart contract::
				//! execute again if tryCommit fails.
				while(coin->get_bal_m(s_id, &bal, t_ID, 
							&t_stamp, conf_list) == false)
				{
					aCount[t_ID]++;
				}
			}

			if(tmp.compare("send") == 0)
			{
				//! Sender ID
				ss >> tmp;
				int s_id = stoi(tmp);

				//! Reciver ID
				ss >> tmp;
				int r_id = stoi(tmp);

				//! Ammount to send
				ss >> tmp;
				int amt  = stoi(tmp);
				int v = coin->send_m(t_ID, s_id, r_id, 
										amt, &t_stamp, conf_list);
				//! execute again if tryCommit fails
				while(v != 1 )
				{
					if(v == -1)
					{
						//! invalid AU:sender does't 
						//! have sufficent bal to send.
						flag = false;
						break;                                    
					}
					aCount[t_ID]++;
					v = coin->send_m(t_ID, s_id, r_id, 
										amt, &t_stamp, conf_list);
				}
			}
			if(tmp.compare("vote") == 0)
			{
				ss >> tmp;
				int vID = stoi(tmp);//! voter ID
				ss >> tmp;
				int pID = stoi(tmp);//! proposal ID
				int v = ballot->vote_m(vID, pID, &t_stamp, conf_list);
				while( v != 1 )
				{					
					if(v == -1)
					{
						//! invalid AU
						flag = false;
						break;                                    
					}
					aCount[t_ID]++;
					v = ballot->vote_m(vID, pID, &t_stamp, conf_list);
				}
			}
			if(tmp.compare("delegate") == 0)
			{
				ss >> tmp;
				int sID = stoi(tmp);//! Sender ID
				ss >> tmp;
				int rID = stoi(tmp);//! Reciver ID

				//! execute again if tryCommit fails
				int v = ballot->delegate_m(sID, rID, &t_stamp, conf_list);	
				while( v != 1 )
				{
					if(v == -1)
					{
						//! invalid AU:
						flag = false;
						break;                                    
					}
					aCount[t_ID]++;
					v = ballot->delegate_m(sID, rID, &t_stamp, conf_list);
				}
			}
			if(tmp.compare("bid") == 0)
			{
				ss >> tmp;
				int payable = stoi(tmp);//! payable
				ss >> tmp;
				int bID = stoi(tmp);//! Bidder ID
				ss >> tmp;
				int bAmt = stoi(tmp);//! Bidder value
				int v = auction->bid_m(payable, bID, bAmt, &t_stamp, conf_list);
				while(v != 1)
				{
					if(v == -1)
					{
						flag = false;//! invalid AU.
						break;                                    
					}
					aCount[0]++;
					v = auction->bid_m(payable, bID, bAmt, &t_stamp, conf_list);
				}
			}
			if(tmp.compare("withdraw") == 0)
			{
				ss >> tmp;
				int bID = stoi(tmp);//! Bidder ID

				int v = auction->withdraw_m(bID, &t_stamp, conf_list);
				while(v != 1)
				{
					if(v == -1)
					{
						flag = false;//! invalid AU.
						break;                                    
					}
					aCount[0]++;
					v = auction->withdraw_m(bID, &t_stamp, conf_list);
				}
			}
			if(tmp.compare("auction_end") == 0)
			{
				int v = auction->auction_end_m(&t_stamp, conf_list);
				while(v != 1)
				{
					if(v == -1)
					{
						flag = false;//! invalid AU.
						break;                                    
					}
					aCount[0]++;
					v = auction->auction_end_m(&t_stamp, conf_list);
				}
			}
			
			//! graph construction for committed AUs.
			if (flag == true)
			{
				mAUT[AU_ID-1] = t_stamp;
				gNodeCount++;
				//! get respective trans conflict list using lib fun
				//list<int>conf_list = lib->get_conf(t_stamp);
				
				//!::::::::::::::::::::::::::::::::::
				//! Remove all the time stamps from :
				//! conflict list, added because    :
				//! of initilization and creation   :
				//! of shared object in STM memory. :
				//!::::::::::::::::::::::::::::::::::
				int TSRemove = CoinSObj+(2*nVoter)+nProposal+3;
				for(int y = 0; y <= TSRemove; y++)
					conf_list.remove(y);
			
				//! statrt clock to get time taken by this.thread 
				//! to add edges and node to conflict grpah.
				auto gstart = thTimer._timeStart();
				
				//!------------------------------------------
				//! conf_list come from contract fun using  !
				//! pass by argument of get_bel() and send()!
				//!------------------------------------------
				//! when AU_ID conflict is empty.
				if(conf_list.begin() == conf_list.end())
				{
					Graph:: Graph_Node *tempRef;
					cGraph->add_node(AU_ID, t_stamp, &tempRef);
				}

				for(auto it = conf_list.begin(); it != conf_list.end(); it++)
				{
					int i = 0;
					//! find the conf_AU_ID 
					//! in map table given 
					//! conflicting time-stamp.
					while(*it != mAUT[i])
					i = (i+1)%numAUs; 

					//! because array index start 
					//! with 0 and index+1 
					//! respresent AU_ID.
					int cAUID   = i+1;
					
					//! conflicting AU_ID
					//! with this.AU_ID.
					int cTstamp = mAUT[i];
					
					 //! edge from conf_AU_ID to AU_ID.
					if(cTstamp  < t_stamp)
						cGraph->add_edge(cAUID, AU_ID, cTstamp, t_stamp);
					
					//! edge from AU_ID to conf_AU_ID.
					if(cTstamp > t_stamp)
						cGraph->add_edge(AU_ID, cAUID, t_stamp, cTstamp);
				}
				gTtime[t_ID] = gTtime[t_ID] + thTimer._timeStop(gstart);
			}
			//! reset flag for next AU.
			flag   = true;
			//! get the current index to 
			//! execute, and increment it.
			curInd = currAU++;
			conf_list.clear();
		}

		mTTime[t_ID] = mTTime[t_ID] + thTimer._timeStop(start);
	}

	//!-------------------------------
	//!FINAL STATE OF ALL THE SHARED |
	//!OBJECT. Once all AUs executed.|
	//!-------------------------------
	void finalState()
	{
		//coin state
		list<int>cList;	int total = 0;
		for(int sid = 1; sid <= CoinSObj; sid++) 
		{
			int bal = 0, ts;
			coin->get_bal_m(sid, &bal, 0, &ts, cList);
			mCoinState[sid] = bal;
		}
		
		for(int id = 1; id <= nVoter; id++) 
			ballot->state_m(id, true, mBallotVotState);//for voter state

		for(int id = 1; id <= nProposal; id++) 
			ballot->state_m(id, false, mBallotProState);//for Proposal state
		
		auction->state_m(&mHBidder, &mHBid);//Auction state
	}

	~Miner() { };
};
/*************************Miner code ends**************************************/







/*************************Validator code begins********************************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Class "Validator" CREATE a POOL of n-validator-THREAD !
! "concValidator()" CALLED BY validator-THREAD TO       !
! PERFROM OPERATIONS of RESPECTIVE AUs.  THREAD 0 IS    !
! CONSIDERED AS MINTER-THREAD (SMART CONTRACT DEPLOYER) !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
class Validator
{
public:
	Validator()
	{
		eAUCount = 0;
		
		//! thread id represents index location.
		vTTime   = new float_t[nThread+1];

		status = new std::atomic<int>[nThread+1];
		Gref   = new Graph::Graph_Node*[nThread+1];

		int i = 0;
		for( ; i < nThread; i++)
		{
			status[i] = 0;
			Gref[i]   = NULL;
			vTTime[i] = 0;	
		}
		vTTime[i] = 0;
	};
	
	//!-------------------------------------------------
	//! CREATE MASTER THREADS: CREATES n WORKER        !
	//! THREADs TO EXECUTE VALID AUs IN CONFLICT GRAPH.!
	//!-------------------------------------------------
	void mainValidator()
	{
		for(int i = 0; i < nThread; i++) vTTime[i] = 0;
		eAUCount = 0;
	
		Timer Ttimer;
		ballot->reset();
		auction->reset();
		coin->reset();
		
		//! initialization of account with fixed ammount;
		//! mint_val() function is serial.
		int bal = InitBalance, total = 0;
		for(int sid = 1; sid <= CoinSObj; sid++) 
		{
			//! 5000 is contract deployer.
			bool v = coin->mint(5000, sid, bal);
			total  = total + bal;
		}
		//! giveRightToVote() function is serial.
		for(int voter = 1; voter <= nVoter; voter++) 
		{
			//! 10000 is chairperson.
			ballot->giveRightToVote(10000, voter);
		}

		//!----------------------------------------------------
		//! MASTER THREAD CREATE n VALIDATOR THREADS          !
		//!----------------------------------------------------
		//!Start clock
		double start = Ttimer.timeReq();
		
		thread master = thread(concValidator, 0 );
		master.join();
		
		//!Stop clock
		tTime[1] = Ttimer.timeReq() - start;

		//! print the final state of the
		//! shared objects by validator.
		finalState();
	}

	//!--------------------------------------------------------
	//! The function to be executed by all Validator threads. !
	//!--------------------------------------------------------
	static void concValidator( int t_ID )
	{
		Timer Ttimer;
		//! start timer to get time taken by this thread.
		auto start = Ttimer._timeStart();

		//! ONLY MASTER THREAD WILL EXECUTE IT.
		if(t_ID == 0)
		{
			thread POOL[nThread+1];
			bool tCratFlag = true;//! POOL thread creation flag.
			Graph::Graph_Node *mVItr;
			while(true)
			{
				if(tCratFlag == true)
				{
					//! Creating n POOL Threads
					for(int i = 1; i <= nThread; i++)
					{
						POOL[i] = thread(concValidator, i);
					}
					tCratFlag = false;
				}
				//! All Valid AUs executed.
				if(eAUCount == gNodeCount)
				{
					for(int i = 1; i <= nThread; i++)
					{
						//! -1 = threads can join now.
						status[i] = -1;
					}
					
					//! POOL thread join.
					for(int i = 1; i <= nThread; i++)
					{
						POOL[i].join( );
					}
					break;
				}
				mVItr = nValBG->verHead->next;
				while(mVItr != nValBG->verTail)
				{
					if(mVItr->in_count == 0)
					{
						for(int i = 1; i <= nThread; i++)
						{
							//! 0 = thread is available.
							if(status[i] == 0)
							{
								//! assigning node ref for
								//! thread in pool to execute.
								Gref[i] = mVItr;
								//! 1 = ref is available to execute.
								status[i] = 1;
								break;
							}
						}
					}
					mVItr = mVItr->next;
				}
			}
		}
		//! EXECCUTED BY nThread WORKER THREADS.
		else
		{
			while(true)
			{
				if(status[t_ID] == -1 || eAUCount == gNodeCount) 
					break;//! All task done.
				
				if(status[t_ID] == 1)//! Task available to work on.
				{
					Graph::Graph_Node *verTemp;
					verTemp      = Gref[t_ID];
					if(verTemp->in_count == 0)
					{
						if(verTemp->in_count < 0)
						{
							status[t_ID] = 0;
						}
						else
						{
							//! expected in_degree is 0 then
							//! vertex can be executed if 
							//! not claimed by other thread.
							int expected = 0;
							if(atomic_compare_exchange_strong(
								&(verTemp->in_count), &expected, -1 ) == true)
							{
								verTemp->in_count = -1;
								//! get AU to execute, which is of string type;
								//! listAUs index statrt with 0 => -1.
								istringstream ss(listAUs[(verTemp->AU_ID)-1]);
								string tmp;

								//! AU_ID to Execute.
								ss >> tmp;
								int AU_ID = stoi(tmp);
								//! Function Name (smart contract).
								ss >> tmp;
								if( tmp.compare("get_bal") == 0 )
								{
									//! get balance of SObj/id.
									ss >> tmp;
									int s_id = stoi(tmp);
									int bal  = 0;

									//! get_bal() of smart contract.
									int v = coin->get_bal(s_id, &bal);
									if(v == -1)
									{
										//! -1 = threads must join
										//! bcz miner is malicious.
										for(int i = 1; i <= nThread; i++)
											status[i] = -1;
									}
								}
								if( tmp.compare("send") == 0 )
								{
									//! Sender ID.
									ss >> tmp;
									int s_id = stoi(tmp);

									//! Reciver ID.
									ss >> tmp;
									int r_id = stoi(tmp);

									//! Ammount to Send.
									ss >> tmp;
									int amt = stoi(tmp);
									int v  = coin->send(s_id, r_id, amt);
									if(v == -1)
									{
										//! -1 = threads must join
										//! bcz miner is malicious.
										for(int i = 1; i <= nThread; i++)
											status[i] = -1;
									}
								}
								if(tmp.compare("vote") == 0)
								{
									ss >> tmp;
									int vID = stoi(tmp);//! voter ID
									ss >> tmp;
									int pID = stoi(tmp);//! proposal ID
									int v = ballot->vote(vID, pID);
									if(v == -1)
									{
										//! -1 = threads must join
										//! bcz miner is malicious.
										for(int i = 1; i <= nThread; i++)
											status[i] = -1;
									}
								}
								if(tmp.compare("delegate") == 0)
								{
									ss >> tmp;
									int sID = stoi(tmp);//! Sender ID
									ss >> tmp;
									int rID = stoi(tmp);//! Reciver ID
									int v = ballot->delegate(sID, rID);
									if(v == -1)
									{
										//! -1 = threads must join
										//! bcz miner is malicious.
										for(int i = 1; i <= nThread; i++)
											status[i] = -1;
									}
								}
								if(tmp.compare("bid") == 0)
								{
									ss >> tmp;
									int payable = stoi(tmp);//! payable
									ss >> tmp;
									int bID = stoi(tmp);//! Bidder ID
									ss >> tmp;
									int bAmt = stoi(tmp);//! Bidder value
									int v = auction->bid(payable, bID, bAmt);
								}
								if(tmp.compare("withdraw") == 0)
								{
									ss >> tmp;
									int bID = stoi(tmp);//! Bidder ID
									int v = auction->withdraw(bID);
								}
								if(tmp.compare("auction_end") == 0)
								{
									bool v = auction->auction_end( );
								}
								
								//!-----------------------------------------
								//!change indegree of out edge nodes (node !
								//! having incomming edge from this node). !
								//!-----------------------------------------
								Graph::EdgeNode *eTemp = verTemp->edgeHead->next;
								while( eTemp != verTemp->edgeTail)
								{
									Graph::Graph_Node* refVN =
												(Graph::Graph_Node*)eTemp->ref;
									refVN->in_count--;
									eTemp = eTemp->next;
								}
								//! num of Valid AUs executed is eAUCount+1.
								eAUCount++;
							}
						}
					}
					status[t_ID] = 0;
				}
			}
		}
		vTTime[t_ID] = vTTime[t_ID] + Ttimer._timeStop( start );
	}


	//!-------------------------------
	//!FINAL STATE OF ALL THE SHARED |
	//!OBJECT. Once all AUs executed.|
	//!-------------------------------
	void finalState()
	{
		//coin state
		for(int sid = 1; sid <= CoinSObj; sid++) 
		{
			int bal = 0, ts;
			bool v  = coin->get_bal(sid, &bal);
			vCoinState[sid] = bal;
		}

		for(int id = 1; id <= nVoter; id++) 
			ballot->state(id, true, vBallotVotState);//for voter state

		for(int id = 1; id <= nProposal; id++) 
			ballot->state(id, false, vBallotProState);//for Proposal state
		
		auction->state(&vHBidder, &vHBid); //auction state
	}

	~Validator() { };
};
/*************************Validator code ends**********************************/





//atPoss:: from which double-spending Tx to be stored at end of the list.
bool addMFS(int atPoss)//add malicious final state with double-spending Tx
{
	istringstream ss(listAUs[atPoss-2]);
	string trns1;
	ss >> trns1; //! AU_ID to Execute.
	int AU_ID1 = stoi(trns1);
	ss >> trns1;//function name
	ss >> trns1; //! Sender ID.
	int s_id = stoi(trns1);
	ss >> trns1; //! Reciver ID.
	int r_id = stoi(trns1);
	ss >> trns1; //! Ammount to send.
	int amtAB  = stoi(trns1);

	istringstream ss1(listAUs[atPoss-1]);
	ss1 >> trns1; //! AU_ID to Execute.
	int AU_ID2 = stoi(trns1);
	ss1 >> trns1;//function name
	ss1 >> trns1; //! Sender ID.
	int s_id1 = stoi(trns1);
	ss1 >> trns1; //! Reciver ID.
	int r_id1 = stoi(trns1);
	ss1 >> trns1; //! Ammount to send.
	int amtAC  = stoi(trns1);


	cGraph->remove_AU_Edge(cGraph, AU_ID1);
	cGraph->remove_AU_Edge(cGraph, AU_ID2);

	mCoinState[s_id]  = 1000;
	mCoinState[r_id]  = 1000;
	mCoinState[r_id1] = 1000;


	amtAB = 950;
	trns1 = to_string(AU_ID1)+" send "+to_string(s_id)+" "+to_string(r_id)+" "+to_string(amtAB)+"\n";
	listAUs[AU_ID1-1] =  trns1;
	
	amtAC = 100;
	trns1 = to_string(AU_ID2)+" send "+to_string(s_id)+" "+to_string(r_id1)+" "+to_string(amtAC)+"\n";
	listAUs[AU_ID2-1] =  trns1;

	mCoinState[s_id]  -= amtAB;
	mCoinState[r_id]  += amtAB;
	mCoinState[r_id1] += amtAC;
return true;
}

bool stateVal() {
	bool flag = false;
//	cout<<"\n"<<pl<<"Object \tMiner \t\tValidator"<<endl;
	for(int sid = 1; sid <= CoinSObj; sid++) {
//		cout<<sid<<" \t \t"<<mCoinState[sid]
//			<<" \t\t"<<vCoinState[sid]<<endl;
		if(mCoinState[sid] != vCoinState[sid]) flag = true;
	}
//	cout<<"\n"<<pl<<"Prop ID \tMiner \t\tValidator"<<endl;
	for(int pid = 0; pid < nProposal; pid++) {
//		cout<<pid+1<<" \t \t"<<mBallotProState[pid]
//			<<" \t\t"<<vBallotProState[pid]<<endl;
		if(mBallotProState[pid] != vBallotProState[pid]) flag = true;
	}
//	cout<<"\n"<<pl<<"Voter ID \tMiner \t\tValidator"<<endl;
	for(int vid = 0; vid < nVoter; vid++) {
//		cout<<vid+1<<" \t \t"<<mBallotVotState[vid]
//			<<" \t\t"<<vBallotVotState[vid]<<endl;
		if(mBallotVotState[vid] != vBallotVotState[vid]) flag = true;
	}
	
	if(mHBidder != vHBidder || mHBid != vHBid) flag = true;
//	cout<<pl<<"     Miner Auction Winer "+to_string(mHBidder)
//			+" |  Amount "+to_string(mHBid);
//	cout<<"\n Validator Auction Winer "+to_string(vHBidder)
//			+" |  Amount "+to_string(vHBid);
//	cout<<"\n"<<pl;
	return flag;
}



/*************************Main Fun code begins*********************************/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
/*!!!!!!!!!!!!!!!   main() !!!!!!!!!!!!!!!!!!*/
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
int main( )
{
	cout<<pl<<"OSTM Miner and Fork-Join SCV\n";
	cout<<"-----------------------------\n";

	//! list holds the avg time taken by miner and validator
	//!  threads for multiple consecutive runs of the algorithm.
	list<double>mItrT;         
	list<double>vItrT;	
	int totalDepInG  = 0; //to get total number of dependencies in graph;
	int totalRejCont = 0; //number of validator rejected the blocks;
	int maxAccepted  = 0;
	int totalRun     = NumBlock; //at least 2
	FILEOPR file_opr;
	
	//! read from input file::
	int input[8] = {0};
	file_opr.getInp(input);
	nThread   = input[0]; // # of threads; should be one for serial;
	numAUs    = input[1]; // # of AUs or Transactions;
	CoinSObj  = input[2]; // # Coin Account Shared Object.
	nProposal = input[3]; // # Ballot Proposal Shared Object.
	nVoter    = input[4]; // # Ballot Voter Shared Object.
	nBidder   = input[5]; // # Auction Bidder Shared Object.
	bidEndT   = input[6]; // # Auction Bid End Time.
	lemda     = input[7];

	if(CoinSObj > maxCoinAObj) {
		CoinSObj = maxCoinAObj;
		cout<<"Max number of Coin Shared Object can be "<<maxCoinAObj<<"\n";
	}
	if(nProposal > maxPropObj) {
		nProposal = maxPropObj;
		cout<<"Max number of Proposal Shared Object can be "<<maxPropObj<<"\n";
	}	
	if(nVoter > maxVoterObj) {
		nVoter = maxVoterObj;
		cout<<"Max number of Voter Shared Object can be "<<maxVoterObj<<"\n";
	}
	if(nBidder > maxBidrObj) {
		nBidder = maxBidrObj;
		cout<<"Max number of Bid Shared Object can be "<<maxBidrObj<<"\n";
	}
	if(bidEndT > maxbEndT) {
		bidEndT = maxbEndT;
		cout<<"Max Bid End Time can be "<<maxbEndT<<"\n";
	}

	//used for state validation
	mCoinState      = new int[CoinSObj];
	vCoinState      = new int[CoinSObj];
	mBallotProState = new int [nProposal];
	vBallotProState = new int [nProposal];
	mBallotVotState = new int [nVoter];
	vBallotVotState = new int [nVoter];

	for(int numItr = 0; numItr < totalRun; numItr++)
	{
		lib = new OSTM(tb);
		
 		//! generates AUs (i.e. trans to be executed by miner & validator).
		file_opr.genAUs(input, CFCount, BFCount, AFConut, listAUs);

		mAUT = new std::atomic<int>[numAUs];
		for(int i = 0; i< numAUs; i++) mAUT[i] = 0;

		//MINER
		Miner *miner = new Miner(0);
		miner ->mainMiner();
		
		if(lemda != 0) bool rv = addMFS(NumOfDoubleSTx);

		int totalEdginBG = cGraph->print_grpah();

		//give dependenices in the graph.
		if( numItr > 0 ) totalDepInG += totalEdginBG;

		//VALIDATOR
		if(MValidation == true)
		{
			int acceptCount = 0, rejectCount = 0;
			for(int nval = 0; nval < numValidator; nval++)
			{
				for(int p = 0; p < nProposal; p++)vBallotProState[p]= 0;
				for(int v = 0; v < nVoter; v++)   vBallotVotState[v]= 0;
				for(int c = 0; c < CoinSObj; c++) vCoinState[c]     = 0;

				Validator *validator = new Validator();
				nValBG = NULL;
				nValBG = new Graph;
				cGraph->copy_graph(nValBG);

				//If the miner is malicious this
				//fun remove an edge from graph.
				if(malMiner == true) {
					int eTR = ceil((totalEdginBG * lemda)/100);
					for(int r = 0; r < eTR; r++)
						nValBG->remove_Edge(nValBG);
				}

				validator ->mainValidator();

				//State Validation
				bool flag = stateVal();
				if(flag == true) rejectCount++;
				else acceptCount++;
				mm = false;
			}
			if(numItr > 0 && malMiner == true) {
				totalRejCont += rejectCount;
				if(maxAccepted < acceptCount ) maxAccepted = acceptCount;
			}
		}
		else
		{
			Validator *validator = new Validator();
			nValBG = new Graph;
			cGraph->copy_graph(nValBG);
			validator ->mainValidator();

			//State Validation
			bool flag = stateVal();
			if(flag == true) cout<<"\nBlock Rejected by Validator";
		}
		int abortCnt = 0;
		for( int iii = 0; iii < nThread; iii++ ) {
			abortCnt = abortCnt + aCount[iii];
		}

		float_t gConstT = 0;
		for(int ii = 0; ii < nThread; ii++) gConstT += gTtime[ii];
//		cout<<"\nAvg Grpah Time= "<<gConstT/nThread<<" microseconds";

		//! total valid AUs among List-AUs executed 
		//! by Miner & varified by Validator.
		int vAUs = numAUs - aCount[0];
		if(numItr > 0)
			file_opr.writeOpt(nThread, numAUs, tTime, mTTime, 
			                  vTTime, aCount, vAUs, mItrT, vItrT);

//		for(int pid = 0; pid < nProposal; pid++) mBallotProState[pid] = 0;
//		for(int vid = 0; vid < nVoter; vid++)    mBallotVotState[vid] = 0;
//		for(int cid = 0; cid < CoinSObj; cid++)  mCoinState[cid]      = 0;
		listAUs.clear();
		lib = NULL;
		delete miner;
		miner = NULL;
		delete cGraph;
		cGraph = NULL;
	}
	//! to get total avg miner and validator
	//! time after number of totalRun runs.
	double tAvgMinerT = 0, tAvgValidT = 0;
	auto mit = mItrT.begin();
	auto vit = vItrT.begin();
	for(int j = 1; j < totalRun; j++) {
		tAvgMinerT = tAvgMinerT + *mit;
		tAvgValidT = tAvgValidT + *vit;
		mit++;
		vit++;
	}
	tAvgMinerT = tAvgMinerT/(totalRun-1);
	tAvgValidT = tAvgValidT/(totalRun-1);
	cout<<"    Total Avg Miner       = "<<tAvgMinerT<<" microseconds";
	cout<<"\nTotal Avg Validator       = "<<tAvgValidT<<" microseconds";
	cout<<"\n-----------------------------\n";
	cout<<"Avg Dependencies in Graph = "<<totalDepInG/(totalRun-1);
	cout<<"\n-----------------------------\n";
	cout<<"\nAvg Number of Validator Accepted the Block = "
		<<(numValidator-(totalRejCont/(totalRun-1)));
	cout<<"\nAvg Number of Validator Rejcted the Block  = "
		<<totalRejCont/(totalRun-1);
	cout<<"\nMax Validator Accepted any Block = "<<maxAccepted;
	cout<<"\n"<<endl;

	mItrT.clear();
	vItrT.clear();
	delete mTTime;
	delete vTTime;
	delete aCount;
	return 0;
}
/*************************Main Fun code ends***********************************/
